// Dart wrapper over the Rewind C shim. The raw `@Native` externals are
// GENERATED by ffigen into rewind_obs_bindings.g.dart (see ffigen.yaml —
// regenerate with `dart run ffigen --config ffigen.yaml` after any
// rewind_obs.h change); this file only adds the ergonomic layer: UTF-8
// marshalling, out-buffer allocation, and bool/int bridging. The shim is
// compiled and bundled by hook/build.dart as the code asset
// `package:rewind/rewind_obs.dart`, which the generated bindings target —
// no manual DynamicLibrary.open / per-OS library placement needed.
library;

import 'dart:ffi';
import 'package:ffi/ffi.dart';

import 'rewind_obs_bindings.g.dart' as b;

/// Size of the buffer allocated for `rewind_list_displays`'s JSON
/// out-param. Comfortably covers the display counts Rewind targets (a
/// handful of monitors); the shim reports truncation via a non-zero return
/// rather than silently corrupting output if it's ever exceeded.
const int _kDisplayListBufferSize = 4096;

/// Size of the buffer allocated for `rewind_list_capturable_apps`'s JSON
/// out-param. Larger than [_kDisplayListBufferSize]: a busy desktop can
/// easily have a few dozen apps with on-screen windows, and each entry now
/// carries an absolute .icns icon path on top of the bundle id + name.
const int _kAppListBufferSize = 65536;

/// Size of the buffer allocated for `rewind_perf_stats_json`'s JSON
/// out-param — the object has a fixed, small set of numeric fields, so this
/// comfortably covers it with headroom.
const int _kPerfStatsBufferSize = 512;

/// Size of the buffer allocated for `rewind_list_audio_inputs_json`'s JSON
/// out-param. Mirrors [_kDisplayListBufferSize]: a real machine has at most
/// a handful of microphones (built-in + a few USB/Bluetooth/virtual ones).
const int _kAudioInputListBufferSize = 4096;

/// Runs [body] with [value] marshalled to a NUL-terminated UTF-8 C string,
/// freeing it afterwards — the repeated pattern behind every string-taking
/// shim call below.
T _withUtf8<T>(String value, T Function(Pointer<Char> p) body) {
  final p = value.toNativeUtf8();
  try {
    return body(p.cast<Char>());
  } finally {
    malloc.free(p);
  }
}

/// Calls a `(char *json_out, int json_cap)` shim function with a
/// [capacity]-byte scratch buffer and returns the JSON string, or null when
/// the shim reports failure — the repeated pattern behind every
/// JSON-out-param call below.
String? _jsonOut(int capacity, int Function(Pointer<Char> p, int cap) call) {
  final buf = malloc<Uint8>(capacity);
  try {
    final p = buf.cast<Char>();
    if (call(p, capacity) != 0) return null;
    return p.cast<Utf8>().toDartString();
  } finally {
    malloc.free(buf);
  }
}

/// Thin Dart wrapper over the shim. In pure `dart test` (no native assets
/// built) these calls are never invoked, so tests stay hermetic.
class RewindObs {
  const RewindObs._();

  /// Kept for API compatibility with the previous DynamicLibrary loader.
  /// With native assets the shim is always bundled; returns an instance.
  static RewindObs? tryLoad() => const RewindObs._();

  int init({required String outDir, required int seconds}) =>
      _withUtf8(outDir, (p) => b.rewind_obs_init(p, seconds));

  int startBuffer() => b.rewind_start_buffer();
  int stopBuffer() => b.rewind_stop_buffer();

  /// Tears down the capture source, keeping the target preference. See
  /// `rewind_capture_suspend` in native/shim/rewind_obs.h.
  int captureSuspend() => b.rewind_capture_suspend();

  /// Recreates the capture source from the remembered target preference. See
  /// `rewind_capture_resume` in native/shim/rewind_obs.h.
  int captureResume() => b.rewind_capture_resume();

  /// Starts a manual recording into [outDir]. Returns 0 on success.
  int startRecording(String outDir) =>
      _withUtf8(outDir, b.rewind_start_recording);

  /// Stops the manual recording started by [startRecording], returning the
  /// recorded file's path, or null if none was in progress / on failure.
  String? stopRecording() {
    final r = b.rewind_stop_recording();
    if (r == nullptr) return null;
    return r.cast<Utf8>().toDartString();
  }

  /// Apply a new replay-buffer length (used on per-game switch).
  int setBufferSeconds(int seconds) => b.rewind_set_buffer_seconds(seconds);

  int shutdown() => b.rewind_obs_shutdown();

  /// Description of the most recent shim-level failure, or "" if none.
  String lastError() => b.rewind_last_error().cast<Utf8>().toDartString();

  String? saveClip(String outDir) => _withUtf8(outDir, (p) {
        final r = b.rewind_save_clip(p);
        if (r == nullptr) return null;
        return r.cast<Utf8>().toDartString();
      });

  /// Raw JSON array from `rewind_list_displays`, or null on failure.
  String? listDisplaysJson() =>
      _jsonOut(_kDisplayListBufferSize, b.rewind_list_displays);

  int setCaptureDisplay(String uuid) =>
      _withUtf8(uuid, b.rewind_set_capture_display);

  /// Raw JSON array from `rewind_list_capturable_apps`, or null on failure.
  String? listCapturableAppsJson() =>
      _jsonOut(_kAppListBufferSize, b.rewind_list_capturable_apps);

  /// Selects an application to capture, or reverts to display capture when
  /// [bundleId] is null.
  int setCaptureApp(String? bundleId) =>
      _withUtf8(bundleId ?? '', b.rewind_set_capture_app);

  /// Selects a specific window (CGWindowID) to capture; 0 reverts to the
  /// remaining app/display preference.
  int setCaptureWindow(int windowId) => b.rewind_set_capture_window(windowId);

  /// Enables/disables microphone capture (mixed into clips alongside the
  /// always-on system audio).
  int setMicEnabled(bool enabled) => b.rewind_set_mic_enabled(enabled ? 1 : 0);

  /// Raw JSON array from `rewind_list_audio_inputs_json`, or null on
  /// failure.
  String? listAudioInputsJson() =>
      _jsonOut(_kAudioInputListBufferSize, b.rewind_list_audio_inputs_json);

  /// Selects the microphone input device, or reverts to the system default
  /// when [uid] is null.
  void setMicDevice(String? uid) =>
      _withUtf8(uid ?? '', b.rewind_set_mic_device);

  /// Sets the microphone recording-level multiplier (1.0 = 100%, clamped by
  /// the shim to 0.0-2.0).
  int setMicVolume(double volume) => b.rewind_set_mic_volume(volume);

  /// Enables/disables live mic monitoring (through the speakers/
  /// headphones) — engine-only, never persisted.
  int setMicMonitoring(bool enabled) =>
      b.rewind_set_mic_monitoring(enabled ? 1 : 0);

  /// Sets capture framerate and output-height cap (0 = source). Applied at
  /// init; call before it.
  int setCaptureQuality(int fps, int maxHeight) =>
      b.rewind_set_capture_quality(fps, maxHeight);

  /// Sets the system/app audio mode (0 = off, 1 = all, 2 = app).
  int setAudioMode(int mode) => b.rewind_set_audio_mode(mode);

  /// Sets the game/desktop-audio recording-level multiplier (1.0 = 100%,
  /// clamped by the shim to 0.0-2.0).
  int setGameVolume(double volume) => b.rewind_set_game_volume(volume);

  /// Enables/disables the mic auto-leveling filter chain
  /// (compressor->limiter).
  int setMicLeveling(bool enabled) =>
      b.rewind_set_mic_leveling(enabled ? 1 : 0);

  /// Enables/disables the RNNoise mic noise-suppression filter.
  int setMicNoiseSuppression(bool enabled) =>
      b.rewind_set_mic_noise_suppression(enabled ? 1 : 0);

  /// Raw JSON object from `rewind_audio_levels_json` (live mic/game dBFS
  /// levels for the mic-test meter), or null on failure. Small fixed-field
  /// object, so the perf-stats buffer size comfortably covers it.
  String? audioLevelsJson() =>
      _jsonOut(_kPerfStatsBufferSize, b.rewind_audio_levels_json);

  /// True if screen-capture permission is currently granted. Safe to poll
  /// repeatedly (e.g. from onboarding UI) — never prompts.
  bool preflightScreenPermission() =>
      b.rewind_preflight_screen_permission() != 0;

  /// Triggers the OS permission prompt where one exists (a no-op if already
  /// granted, or already asked and denied). Returns the resulting granted
  /// state.
  bool requestScreenPermission() => b.rewind_request_screen_permission() != 0;

  /// Raw JSON object from `rewind_perf_stats_json` (CPU/RSS + libobs frame
  /// counters), or null on failure. See [PerfMonitor] (lib/src/log/) for the
  /// periodic sampler that calls this.
  String? perfStatsJson() =>
      _jsonOut(_kPerfStatsBufferSize, b.rewind_perf_stats_json);
}
