#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Fetches a pinned libobs Windows SDK for Rewind's C shim into
  native/third_party/obs/ (git-ignored), matching the layout hook/build.dart
  and native/shim/rewind_obs.c expect. Idempotent: skips work when the
  stamp file matches the pinned tag + recipe version.

.DESCRIPTION
  Unlike macOS (tools/fetch_libobs.sh, which builds libobs from source),
  this script does NOT build anything. There is no upstream "Windows SDK"
  package (headers + import libs) for libobs — obsproject only publishes
  either full source, or a prebuilt end-user RUNTIME zip (DLLs only, no
  headers, no .lib import libraries). So this script assembles one itself,
  from two official, pinned artifacts of the same obs-studio GitHub
  release:

    1. "OBS-Studio-<tag>-Windows-x64.zip" — the official prebuilt Windows
       portable build. Source of every .dll/.exe this script keeps
       (obs.dll, the win-capture/win-wasapi/obs-ffmpeg/obs-x264/obs-nvenc/
       obs-qsv11 plugin DLLs, the obs-ffmpeg-mux.exe helper, and their
       runtime dependencies) plus their data/ directories. Everything
       OBS Studio's own GUI needs (Qt6, CEF/obs-browser, decklink, aja,
       obs-websocket, obs-outputs, frontend-tools, ...) is deliberately
       left behind — Rewind never runs the OBS GUI, only libobs as a
       library, and shipping that would multiply the install size for
       nothing.
    2. "OBS-Studio-<tag>-Sources.tar.gz" — the same tag's full source
       tarball, used ONLY for its libobs/**/*.h public headers (no source
       files are compiled). obsconfig.h — normally generated by CMake at
       configure time from libobs/obsconfig.h.in — doesn't exist in either
       artifact, so this script synthesizes a minimal one (see
       Write-ObsConfigHeader below); the values are inert unless something
       includes OBS_INSTALL_DATA_PATH, which Rewind's shim never does.
    3. obs.lib (the MSVC import library needed to link against obs.dll) is
       generated from the downloaded obs.dll itself via `dumpbin /exports`
       + a synthesized .def file + `lib.exe` — the standard technique for
       producing an import lib when only a DLL is available. REQUIRES
       dumpbin.exe and lib.exe on PATH, i.e. a Visual Studio "Developer"
       shell/environment (in CI: the ilammy/msvc-dev-cmd action; locally:
       "Developer PowerShell for VS 2022", or run
       `& "${env:ProgramFiles}\Microsoft Visual Studio\...\vcvars64.bat"`
       first).

  Pinned to the SAME libobs tag as macOS (see tools/fetch_libobs.sh's
  OBS_TAG) so behavior/encoder-id assumptions stay comparable across
  platforms. If you bump one, bump the other and re-verify encoder ids
  (see native/shim/README.md's Windows section) against the new tag's
  plugins/win-capture, plugins/win-wasapi, plugins/obs-nvenc,
  plugins/obs-qsv11, plugins/obs-x264, plugins/obs-ffmpeg sources — encoder
  ids and settings keys are NOT guaranteed stable across libobs releases.

.NOTES
  Windows only. Run from a Visual Studio Developer PowerShell (or after
  ilammy/msvc-dev-cmd in CI) so dumpbin.exe/lib.exe resolve. Requires
  PowerShell 5.1+ (Expand-Archive) and tar.exe (bundled since Windows 10
  1803 / Server 2019 — used only to pull libobs/ out of the source tarball,
  no git dependency).
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue' # Invoke-WebRequest is dramatically faster with the progress bar off.

# Must match tools/fetch_libobs.sh's OBS_TAG.
$ObsTag = '32.1.2'
# Bumped whenever this script's recipe changes (which files it keeps, how
# obs.lib is generated, etc.) — same purpose as fetch_libobs.sh's
# RECIPE_VERSION: a warm cache from an older recipe must not be reused as
# though it matches a newer one.
#   1: initial cut — win-capture, win-wasapi, obs-ffmpeg, obs-x264,
#      obs-nvenc, obs-qsv11.
$RecipeVersion = 1

$WindowsZipName = "OBS-Studio-$ObsTag-Windows-x64.zip"
$SourcesTarName = "OBS-Studio-$ObsTag-Sources.tar.gz"
$WindowsZipUrl = "https://github.com/obsproject/obs-studio/releases/download/$ObsTag/$WindowsZipName"
$SourcesTarUrl = "https://github.com/obsproject/obs-studio/releases/download/$ObsTag/$SourcesTarName"
# The Sources tarball's single top-level directory (verified against the
# real 32.1.2 release asset — `tar -tzf` lists
# "obs-studio-32.1.2-sources/...").
$SourcesPrefix = "obs-studio-$ObsTag-sources"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$Out = Join-Path $RepoRoot 'native/third_party/obs'
$Work = Join-Path $RepoRoot 'native/third_party/work-windows'
$Stamp = Join-Path $Out '.stamp'
$StampValue = "$ObsTag arch=x64 recipe=$RecipeVersion"

if ((Test-Path $Stamp) -and ((Get-Content $Stamp -Raw).Trim() -eq $StampValue)) {
    Write-Host "libobs $ObsTag (x64) already present in $Out"
    exit 0
}

if (-not $IsWindows) {
    Write-Error "fetch_libobs_windows.ps1 must run on Windows (obs.lib generation needs dumpbin.exe/lib.exe)."
    exit 1
}

# --- Prereqs -----------------------------------------------------------
foreach ($tool in @('dumpbin.exe', 'lib.exe')) {
    if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
        Write-Error @"
$tool not found on PATH. obs.lib is generated from obs.dll's export table
via dumpbin + lib.exe, which need a Visual Studio Developer environment.
Run this script from "Developer PowerShell for VS 2022" (or "x64 Native
Tools Command Prompt"), or in CI, run the ilammy/msvc-dev-cmd action
before this script.
"@
        exit 1
    }
}
if (-not (Get-Command tar.exe -ErrorAction SilentlyContinue)) {
    Write-Error "tar.exe not found on PATH (bundled with Windows 10 1803+ / Server 2019+)."
    exit 1
}

New-Item -ItemType Directory -Force -Path $Work | Out-Null

# --- 1) Download the two pinned release artifacts (cached by filename;
#        this script's own top-of-file stamp check is the real
#        idempotency guard, this just avoids re-downloading ~200MB when
#        iterating locally after a stamp bump). ---------------------------
$zipPath = Join-Path $Work $WindowsZipName
if (-not (Test-Path $zipPath)) {
    Write-Host "Downloading $WindowsZipUrl ..."
    Invoke-WebRequest -Uri $WindowsZipUrl -OutFile $zipPath
}

$srcTarPath = Join-Path $Work $SourcesTarName
if (-not (Test-Path $srcTarPath)) {
    Write-Host "Downloading $SourcesTarUrl ..."
    Invoke-WebRequest -Uri $SourcesTarUrl -OutFile $srcTarPath
}

# --- 2) Extract just what's needed -----------------------------------
$runtimeDir = Join-Path $Work 'runtime'
if (Test-Path $runtimeDir) { Remove-Item -Recurse -Force $runtimeDir }
Write-Host "Extracting $WindowsZipName ..."
Expand-Archive -Path $zipPath -DestinationPath $runtimeDir -Force

$srcDir = Join-Path $Work 'src'
if (Test-Path $srcDir) { Remove-Item -Recurse -Force $srcDir }
New-Item -ItemType Directory -Force -Path $srcDir | Out-Null
Write-Host "Extracting libobs/ headers from $SourcesTarName ..."
# bsdtar (Windows' bundled tar.exe) supports extracting a specific member
# path/prefix without needing --wildcards (a GNU tar-only flag).
tar -xzf $srcTarPath -C $srcDir "$SourcesPrefix/libobs"
if ($LASTEXITCODE -ne 0) { throw "tar extraction of libobs/ failed (exit $LASTEXITCODE)" }

# --- 3) Lay out what Rewind consumes, mirroring tools/fetch_libobs.sh's
#        include/, lib/, obs-plugins/, data/ shape (bin/ added for the
#        DLL closure + helper exe, matching the official runtime layout
#        rewind_obs.c's Windows setup_module_paths()/find_graphics_module_path()
#        expect — see native/shim/README.md). -----------------------------
if (Test-Path $Out) { Remove-Item -Recurse -Force $Out }
New-Item -ItemType Directory -Force -Path "$Out/include" | Out-Null
New-Item -ItemType Directory -Force -Path "$Out/lib" | Out-Null
New-Item -ItemType Directory -Force -Path "$Out/bin/64bit" | Out-Null
New-Item -ItemType Directory -Force -Path "$Out/obs-plugins/64bit" | Out-Null
New-Item -ItemType Directory -Force -Path "$Out/data/libobs" | Out-Null
New-Item -ItemType Directory -Force -Path "$Out/data/obs-plugins" | Out-Null

# include/: every libobs/**/*.h, flattened so obs.h sits directly under
# include/ (same "obs.h directly reachable, util/ and friends as
# subdirectories" shape as the macOS SDK's include/ — see
# tools/fetch_libobs.sh's own report of what it flattens).
$libobsSrc = Join-Path $srcDir "$SourcesPrefix/libobs"
Get-ChildItem -Path $libobsSrc -Recurse -Filter *.h | ForEach-Object {
    $rel = $_.FullName.Substring($libobsSrc.Length + 1)
    $dest = Join-Path "$Out/include" $rel
    New-Item -ItemType Directory -Force -Path (Split-Path $dest -Parent) | Out-Null
    Copy-Item $_.FullName $dest
}

# obsconfig.h: normally CMake-generated from libobs/obsconfig.h.in at
# configure time (see that file for the real template) — synthesized here
# since nothing in this pipeline runs CMake. Values are inert: nothing in
# rewind_obs.c references OBS_INSTALL_DATA_PATH (the only thing obs-config.h
# builds from these), so placeholder values are safe.
Set-Content -Path "$Out/include/obsconfig.h" -Value @'
#pragma once
#define OBS_DATA_PATH "data/libobs"
#define OBS_RELEASE_CANDIDATE 0
#define OBS_BETA 0
'@

# bin/64bit/: obs.dll + the runtime DLLs our kept plugins need, and the
# obs-ffmpeg-mux.exe helper (spawned by the replay_buffer/ffmpeg_muxer
# outputs to write files — see rewind_obs.c's mux_helper_present() doc).
# Deliberately NOT copying obs64.exe/Qt6*/libcef.dll/chrome_*/icon-engines
# etc. — those are OBS Studio's own GUI's dependencies, irrelevant to
# libobs used as a library. The *-test.exe helpers ARE kept: NVENC/QSV/AMF
# availability probing spawns them in an isolated child process rather
# than probing in-process (crash-isolation — a misbehaving driver takes
# down a disposable helper, not Rewind itself); omitting them risks
# hardware encoders silently reporting "unavailable".
$binKeep = @(
    'obs.dll', 'libobs-d3d11.dll', 'libobs-opengl.dll', 'libobs-winrt.dll',
    'w32-pthreads.dll', 'obs-ffmpeg-mux.exe',
    'obs-nvenc-test.exe', 'obs-qsv-test.exe', 'obs-amf-test.exe',
    'avcodec-61.dll', 'avdevice-61.dll', 'avfilter-10.dll', 'avformat-61.dll', 'avutil-59.dll',
    'swresample-5.dll', 'swscale-8.dll', 'libx264-164.dll',
    'librist.dll', 'srt.dll', 'libcurl.dll', 'zlib.dll'
)
foreach ($f in $binKeep) {
    $src = Join-Path $runtimeDir "bin/64bit/$f"
    if (-not (Test-Path $src)) {
        Write-Warning "expected runtime file missing, skipping: bin/64bit/$f (OBS release layout may have changed — check native/shim/README.md)"
        continue
    }
    Copy-Item $src "$Out/bin/64bit/$f"
}

# obs-plugins/64bit/ + data/obs-plugins/<name>/: only the modules Rewind
# actually uses (see native/shim/README.md's Windows section for exactly
# which source/encoder/output ids each provides). NOT coreaudio-encoder —
# deliberately excluded: it only builds on Windows by dynamically loading
# Apple's proprietary CoreAudioToolbox.dll at runtime, which Rewind has no
# license to redistribute and which isn't present on a stock Windows
# machine; ffmpeg_aac (from obs-ffmpeg, already kept) is the Windows audio
# encoder instead.
$pluginsKeep = @('win-capture', 'win-wasapi', 'obs-ffmpeg', 'obs-x264', 'obs-nvenc', 'obs-qsv11')
foreach ($p in $pluginsKeep) {
    $dll = Join-Path $runtimeDir "obs-plugins/64bit/$p.dll"
    if (-not (Test-Path $dll)) {
        throw "required plugin missing from runtime zip: obs-plugins/64bit/$p.dll (OBS release layout may have changed)"
    }
    Copy-Item $dll "$Out/obs-plugins/64bit/$p.dll"

    $dataSrc = Join-Path $runtimeDir "data/obs-plugins/$p"
    if (Test-Path $dataSrc) {
        Copy-Item $dataSrc "$Out/data/obs-plugins/$p" -Recurse
    }
}

# data/libobs/: core effects (shaders) libobs itself needs regardless of
# which plugins are loaded.
Copy-Item (Join-Path $runtimeDir 'data/libobs/*') "$Out/data/libobs/" -Recurse -Force

# --- 4) Generate lib/obs.lib from obs.dll's own export table -------------
# The runtime zip ships no import library (it's an end-user package, not a
# dev SDK) — dumpbin + a synthesized .def + lib.exe is the standard way to
# produce one from just the DLL. Every export libobs.dll advertises is
# extern "C" (obs.h's public API is wrapped `#ifdef __cplusplus extern "C"`),
# so the export table already holds plain, undecorated names — no
# demangling needed.
Write-Host "Generating obs.lib from obs.dll's export table ..."
$obsDll = "$Out/bin/64bit/obs.dll"
$exportsRaw = & dumpbin /exports $obsDll
if ($LASTEXITCODE -ne 0) { throw "dumpbin /exports obs.dll failed (exit $LASTEXITCODE)" }

# Export table lines look like: "          1    0 00012340 obs_startup"
# (ordinal, hint, RVA, name) — anchoring on a leading ordinal number
# excludes the file/section header and summary footer lines dumpbin also
# prints.
$exportNames = $exportsRaw | Select-String -Pattern '^\s*\d+\s+[0-9A-Fa-f]+\s+[0-9A-Fa-f]+\s+(\S+)\s*$' |
    ForEach-Object { $_.Matches[0].Groups[1].Value }

if (-not $exportNames -or $exportNames.Count -eq 0) {
    throw "no exports parsed from obs.dll — dumpbin output format may have changed; inspect it manually"
}
Write-Host "  found $($exportNames.Count) exports"

$defPath = Join-Path $Work 'obs.def'
$defContent = "LIBRARY OBS`r`nEXPORTS`r`n" + ($exportNames -join "`r`n")
Set-Content -Path $defPath -Value $defContent -NoNewline

& lib /def:$defPath /out:"$Out/lib/obs.lib" /machine:x64 | Out-Null
if ($LASTEXITCODE -ne 0) { throw "lib.exe failed to build obs.lib from $defPath (exit $LASTEXITCODE)" }
# lib.exe also emits a matching obs.exp we don't need (only meaningful when
# building the DLL itself, not when consuming it) — drop it so it isn't
# mistaken for something rewind_obs bundling needs.
Remove-Item -Force -ErrorAction SilentlyContinue "$Out/lib/obs.exp"

Set-Content -Path $Stamp -Value $StampValue -NoNewline
Write-Host "libobs $ObsTag (x64) ready in $Out"
